import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/shared/Navbar';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Arzu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="font-poppins">
          <div className="  flex flex-col  min-h-screen font-sans">
            <div>
              <Navbar />
            </div>
            <div className=" -mt-42">{children}</div>
            <div className="absolute bottom-0  text-center w-full">
              {/* <Footer /> */}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
