import '../globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/shared/Navbar';
import { ClerkProvider } from '@clerk/nextjs';
import Footer from '@/components/shared/Footer';
import { CartProvider } from '@/lib/context/cartContext';
import { UserProvider } from '@/lib/context/userContext';

export const metadata: Metadata = {
  title: 'Arzu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="font-poppins">
          <div className="  flex flex-col  min-h-screen justify-between ">
            <CartProvider>
              <div className="z-20">
                <Navbar />
              </div>
              <div className="my-5">{children}</div>
              <div className=" text-center w-full">
                <Footer />
              </div>
            </CartProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
